### ISSUE TITLE
To-do list for 1.0

### ISSUE THREAD

**Issue by ben** [ben/foundry-ironsworn#2]
## What _won't_ be in 1.0

If we don't limit scope, we'll never get there.

- Delve content:
  - Moves & oracles
  - Sites
  - Failure track
  - Rarities
  - Vow threat
- Move-to-move or move-to-oracle linking (i.e. miss-on-Strike -> Pay the Price)
- ~~Co-op mode shared sheets~~
- "Burn momentum" button on chat roll cards
- Including custom moves/oracles on the character sheet

## To-do list for 1.0

- [x] Solo-mode character sheet
  - [x] …that looks good
- [x] A nice roll output card that detects `{d10,d10,d6+...}` rolls
- [x] Stat editing and click-to-roll
- [x] Assets as items
  - [x] Assets expand in place on sheet
  - [x] Clickable rolls where appropriate
  - [x] Health tracks in applicable items
  - [x] …that are rollable
- [x] Asset special cases
  - [x] Ironclad - radio buttons probably
  - [x] [Awaken](https://github.com/ben/foundry-ironsworn/issues/17) 6-health option
- [x] Momentum and debilities
- [x] Bonds track, maybe these are items?
- [x] Experience - earned + spent? Or just on/off?
- [x] Progress items
- [x] Vow items
- [x] Move items
- [x] A macro or script to import data from https://github.com/rsek/datasworn into compendia.
- [x] Shared sheet

**Comment by ben** [comment]
Completed this with #75. 🎉
