### ISSUE TITLE
Asset browser

### ISSUE THREAD

**Issue by ben** [ben/foundry-ironsworn#488]
This is a tracking issue for switching from the built-in compendium browser to a custom one with a tree structure.

- [x] Write the browser (#487)
- [x] Update the styling so that abilities that aren't marked have empty pips (#491)
- [ ] Asset data updates (re-import with fixes):
  - [x] Add a "requirement" field (#495)
  - [ ] Remove category from asset-item names and restore the category display in the collapsed view (#497)
- [x] Reimplement move clicks with a global emitter (#492)
- [x] Browser support for custom assets in the "Custom Assets" folder (#494)
- [ ] Replace the compendium button with the browser button on PC sheets (#497)
